### ISSUE TITLE
Cannot submit several exercises

### ISSUE THREAD

**Issue by glhrmv** [exercism/crystal-test-runner#28]
I have been doing the Crystal track and I'm having trouble submitting 3 exercises due to the test runner. They are: [Binary Search Tree](https://exercism.org/tracks/crystal/exercises/binary-search-tree), [Atbash Cipher](https://exercism.org/tracks/crystal/exercises/atbash-cipher), and [Binary](https://exercism.org/tracks/crystal/exercises/binary). I assume there are more, these are just the ones I've found.

On Binary Search Tree, I have the following code:
```cr
class Node
  getter value : Int32
  property left : Node?
  property right : Node?

  def initialize(@value)
  end

  def insert(value) 
    if @value == value
      return
    end

    if @value < value
      if left = @left
        return left.insert(value)
      end

      @left = Node.new(value)
    end

    if @value > value
      if right = @right
        return right.insert(value)
      end

      @right = Node.new(value)
    end
  end
end
```
As soon as I try to run the tests, I get the following error message:
```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

On Atbash Cipher, I have the following code:
```cr
class AtbashCipher
    private PLAIN = "abcdefghijklmnopqrstuvwxyz"
    private CODE = "zyxwvutsrqponmlkjihgfedcba"
    private CIPHER = Hash(Char, Char).zip(PLAIN.chars, CODE.chars)
    private WORD_SIZE = 5

    def self.encode(input : String) : String
        encoded = ""

        char_count = 0
        input.downcase.delete(' ').each_char do |c|
            char_count += 1
            encoded += CIPHER[c]
            
            if char_count == WORD_SIZE
                char_count = 0
                encoded += ' '
            end
        end
            
        encoded
    end

    def self.decode(input : String) : String
        decoded = ""
        input.downcase.delete(' ').each_char { |c| decoded += CIPHER[c] }
        decoded
    end
end
```

On this one, the tests pass but I am unable to submit. This is what I see on the website:

![image](https://user-images.githubusercontent.com/20033110/144413346-14084196-ce63-4ebf-87e9-f7bdb1907e9d.png)

On Binary, I have the following code:
```cr
class Binary
    def self.to_decimal(binary : String) : Int32
        sol = binary.chars.reverse.reduce({0, 0}) do |acc, c|
            d = c.to_i
            
            if d != 0 || d != 1 
                raise ArgumentError.new()
            end 

            {d * (2 ** acc.last), acc.last + 1}
        end

        sol.first
    end
end
```

When I try to submit, I get the same result as Atbash Cipher -- the tests pass but I am unable to submit. 

I have tried and  successfully completed other exercises since these and I have successfully reran the tests for my previously submitted solutions, so I believe this is an exercise-specific flaw, not an infrastructure-wide error.

**Comment by SleeplessByte** [comment]
cc @ErikSchierboom

**Comment by ErikSchierboom** [comment]
I've just tested it with the `binary-search-tree` exercise, and it does indeed crash:

```
binary-search-tree: testing...
* Reading spec file: /solution/spec/binary_search_tree_spec.cr 📖
Unhandled exception: Found unexpected test case in a test case (Exception)
  from /usr/share/crystal/src/array.cr:2064:15 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
  from ???
* Reading scaffold json 📖
Unhandled exception: Error opening file with mode 'r': '/output/scaffold.json': No such file or directory (File::NotFoundError)
  from /usr/share/crystal/src/crystal/system/file.cr:7:7 in 'new'
  from /usr/share/crystal/src/file.cr:627:12 in 'read'
  from helpers/result_to_json.cr:121:30 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
  from ???
binary-search-tree: done
```

@neenjaw, are you are the author of this test runner, could you perhaps take a look?

**Comment by neenjaw** [comment]
Yea, likely an u expected pattern in the test runner junit output which doesn't match the XML parsers schema or the JSON encoder schema. Will try to take a look this weekend.

**Comment by neenjaw** [comment]
So there are 2 issues I found as these bugs raised are actually separate:
1) @glhrmv's bug: missing the junit error code
2) @ErikSchierboom's bug: error parsing the test file

For number 1, I have a fix

For number 2, I am going to rewrite `scaffold_json.cr` to parse the AST using one of the compiler tools that seem to be relatively undocumented.  This will be able to produce more consistent output for the contents of the test run.

Should be able to open a PR for these this weekend.

**Comment by neenjaw** [comment]
@glhrmv, once #29 is merged, these issues should be resolved.  Thanks for reporting it!

**Comment by neenjaw** [comment]
Fixes merged, should deploy automatically shortly
